export const skills = [
    "Communication",
    "Problem-Solving",
    "Critical Thinking",
    "Time Management",
    "Leadership",
    "Teamwork",
    "Adaptability",
    "Creativity",
    "Decision Making",
    "Conflict Resolution",
    "Negotiation",
    "Public Speaking",
    "Active Listening",
    "Project Management",
    "Presentation Skills",
    "Customer Service",
    "Analytical Thinking",
    "Strategic Planning",
    "Emotional Intelligence",
    "Microsoft Office Suite",
    "Adobe Creative Cloud",
    "SQL",
    "Python",
    "Java",
    "JavaScript",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Git",
    "Agile Methodologies",
    "Scrum",
    "Product Management",
    "Data Analysis",
    "Machine Learning",
    "Artificial Intelligence",
    "Cybersecurity",
    "Cloud Computing",
    "Networking",
    "Technical Support",
    "Graphic Design",
    "Video Editing",
    "Content Creation",
    "Social Media Marketing",
    "Search Engine Optimization",
    "Accounting",
    "Finance",
    "Marketing",
    "Sales",
    "Human Resources",
    "Supply Chain Management",
    "Project Coordination",
    "Event Planning",
    "Language Skills (e.g., Spanish, Mandarin, French)",
    "Cultural Awareness",
    "Entrepreneurship",
    "Funding and Investment",
    "Business Development",
    "Strategic Thinking",
    "Innovation",
    "Risk Management",
    "Continuous Learning",
    "Multitasking",
    "Attention to Detail",
    "Organizational Skills",
    "Flexibility",
    "Resilience",
    "Empathy",
    "Collaboration",
    "Mentoring",
    "Coaching",
    "Training",
    "Facilitation",
    "Instructional Design",
    "Change Management",
    "Sustainability",
    "Environmental Stewardship",
    "Civic Engagement",
    "Volunteer Experience",
    "Outdoor/Adventure Skills",
    "Cooking/Baking",
    "Gardening",
    "Woodworking",
    "Photography",
    "Music",
    "Arts and Crafts",
    "Sports and Athletics",
    "Travel and Cultural Experiences",
    "Wellness and Self-Care",
    "Mindfulness and Meditation",
    "Lifelong Learning",
  ];

  export   const volunteerismOptions = [
    'Environmental Conservation',
    'Animal Welfare',
    'Education and Literacy',
    'Community Development',
    'Disaster Relief',
    'Healthcare',
    'Poverty Alleviation',
    'Arts and Culture',
    'Sports and Recreation',
    'Elderly Care',
    'Youth Development',
    'Women Empowerment',
    'Mental Health Support',
    'Disability Advocacy',
    'Refugee Assistance',
    'Veterans Support',
    'Hunger and Food Security',
    'Homelessness Outreach',
    'Human Rights',
    'Conservation and Sustainability',
    'STEM Education',
    'Domestic Violence Prevention',
    'Abuse and Neglect Prevention',
    'Immigration and Immigrant Services',
    'Racial Equity and Social Justice',
    'LGBTQ+ Support',
    'Disaster Preparedness',
    'Hospice and Palliative Care',
    'Financial Literacy',
    'Entrepreneurship and Job Training',
    'Civic Engagement and Advocacy',
    'Environmental Justice',
    'Wildlife Conservation',
    'Conservation of Natural Resources',
    'Habitat Restoration',
    'Environmental Education',
    'Renewable Energy',
    'Sustainable Agriculture',
    'Urban Gardening and Farming',
    'Animal Rescue and Rehabilitation',
    'Animal Adoption and Fostering',
    'Animal-Assisted Therapy',
    'Literacy and Reading Programs',
    'Tutoring and Mentoring',
    'Early Childhood Education',
    'Special Education Support',
    'STEM Enrichment',
    'Vocational Training',
    'Adult Education',
    'Community Centers and Recreational Programs',
    'Affordable Housing Development',
    'Neighborhood Revitalization',
    'Infrastructure Improvement',
    'Community Organizing',
    'Disaster Response and Recovery',
    'Emergency Preparedness',
    'Search and Rescue',
    'Medical Volunteering',
    'Nursing Home Assistance',
    'Hospice Care',
    'Addiction Recovery Support',
    'Chronic Illness Support',
    'Maternal and Child Health',
    'Microcredit and Microfinance',
    'Job Training and Placement',
    'Financial Counseling',
    'Workforce Development',
    'Small Business Assistance',
    'Art Instruction and Programming',
    'Museum and Gallery Docents',
    'Performing Arts Support',
    'Cultural Festivals and Events',
    'Historic Preservation',
    'Special Needs Recreation',
    'Youth Sports Coaching',
    'Outdoor Adventure Programs',
    'Senior Center Activities',
    'Retirement Community Support',
    'Assisted Living Companionship',
    'Meal Delivery for the Elderly',
    'Youth Mentorship',
    'After-School Programs',
    'Summer Camps',
    'Teen Leadership Development',
    'Gender Equality Advocacy',
    'Reproductive Rights Support',
    'Domestic Violence Counseling',
    'Trafficking Prevention',
    'Immigrant and Refugee Resettlement',
    'Language Interpretation and Translation',
    'Legal Aid and Advocacy',
    'Civil Rights and Liberties',
    'LGBTQ+ Community Support',
    'Military Family Support',
    'Veterans Assistance',
    'Feeding the Hungry',
    'Food Bank Operations',
    'Soup Kitchens and Meal Services',
    'Urban Gardening and Farming',
    'Food Rescue and Redistribution',
    'Clothing and Household Donations',
    'Shelter and Transitional Housing',
    'Street Outreach and Engagement',
    'Supportive Services for the Homeless',
    'Affordable Housing Development',
    'Habitat for Humanity',
  ];